export const FETCH_POSITION = 'FETCH_LOCAL_POSITION';
export const FETCH_POSITION_FAIL = 'FETCH_POSITION_FAIL';
export const FETCH_POSITION_SUCCESS = 'FETCH_POSITION_SUCCESS';

export const FETCH_WEATHER_DATA = 'FETCH_WEATHER_DATA';
export const FETCH_WEATHER_DATA_FAIL = 'FETCH_WEATHER_DATA_FAIL';
export const FETCH_WEATHER_DATA_SUCCESS = 'FETCH_WEATHER_DATA_SUCCESS';

export const SET_SEARCH_TERM = 'SET_SEARCH_TERM';

export const SEARCH_LOCAL_WEATHER = 'SEARCH_LOCAL_WEATHER';
export const SEARCH_LOCAL_WEATHER_FAIL = 'SEARCH_LOCAL_WEATHER_FAIL';
export const SEARCH_LOCAL_WEATHER_SUCCESS = 'SEARCH_LOCAL_WEATHER_SUCCESS';

export const LOADING_WEATHER = 'LOADING_WEATHER';
